---
- name: Install awscli
  unarchive:
    src: "{{ awscli_url }}"
    remote_src: true
    dest: /tmp

- name: Run aws cli install script
  become: true
  command: /tmp/aws/install
  args:
    creates: /usr/local/bin/aws
