---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu1604
    image: ubuntu:16.04
  - name: ubi7
    image: registry.redhat.io/ubi7
provisioner:
  name: ansible
verifier:
  name: testinfra
