jobs:
  test:
    name: molecule test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.x
      - name: Install required Python dependencies
        run: 'pip install docker molecule==2.20.2 molecule[docker]'
      - name: Install required Ruby dependencies
        run: gem install rubocop
      - run: molecule test --all
name: Molecule Test
'on':
  - push
  - pull_request
